package com.rokid.cxrmsamples.dataBeans

enum class UsageType {
    USAGE_TYPE_AUDIO,
    USAGE_TYPE_VIDEO,
    USAGE_TYPE_PHOTO,
    USAGE_TYPE_FILE,
    USAGE_TYPE_AI,
    USAGE_CUSTOM_VIEW,
    USAGE_TYPE_CUSTOM_PROTOCOL,
    USAGE_TYPE_TELEPROMPTER,
    USAGE_TYPE_TRANSLATION,
    USAGE_TYPE_DEVICE_INFORMATION,
    USAGE_TYPE_TTS_NOTIFICATION,
    USAGE_TYPE_LIVE_VIDEO,
    USAGE_TYPE_AR_RECORDING,
    USAGE_TYPE_PSOP_DEMO,
    USAGE_TYPE_P2P_STABILITY_TEST,
}